server:
  port: 8083

spring:
  application:
    name: wallet-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/croesus_db
    username: ${DB_USERNAME:croesus_user}
    password: ${DB_PASSWORD:croesus123}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:croesus}
    password: ${RABBITMQ_PASSWORD:croesus123}

  cloud:
    config:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
    eureka-server-username: ${EUREKA_USERNAME:admin}
    eureka-server-password: ${EUREKA_PASSWORD:admin}
  instance:
    prefer-ip-address: true

# JWT configuration
app:
  jwt:
    secret: ${JWT_SECRET:croesusSecretKeyForJwtTokenGenerationThatShouldBeLongEnoughForHmacSha256}
    expiration-ms: ${JWT_EXPIRATION:86400000} # 24 hours

# Service configurations
services:
  user-service:
    url: ${USER_SERVICE_URL:http://api-gateway:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.bahadircolak.wallet: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG 